upstream backend {
    hash $request_uri;

    server backend-red:80;
    server backend-blue:80;
    server backend-yellow:80;
    server backend-green:80;
}

server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    location / {
        proxy_pass http://backend;
    }
}
